import Phaser from 'phaser';
import {BASE,asset,character,esc,$,bind,toast,type ExplorationState,type Note,download} from './core';
import type {Segment,Hotspot} from './segments';
import {NPCS,type Point,type NpcId} from '../shared/world';
import type {SessionView,DialogueResult} from '../shared/types';
import {launchMiniGame} from './minigames';
import {walkable,pathTo,approach} from './navigation';
export function launchExploration(root:HTMLElement,seg:Segment,data:ExplorationState,save:()=>void,finish:()=>void,home:()=>void){
 let disposed=false,view='home',busy=false,ready=false,session:SessionView|null=null,mode:'ai'|'preset'='ai',active:Hotspot|null=null,near:Hotspot|null=null,miniCleanup:(()=>void)|undefined;let sessionPromise:Promise<void>|null=null;let lastProgress=Date.now(),hintLevel=0;const collected=data.collected[seg.id]??=[];let pendingRequest:{id:string;npc:NpcId;question:string;evidenceId?:string;mode:'ai'|'preset'}|null=null;
 root.innerHTML=`<main class="explore-layout"><section class="explore-map" aria-label="${esc(seg.name)}地图"><div id="explore-canvas"></div><header class="explore-heading"><button id="explore-home" class="glass">‹ 首页</button><div><p>${esc(seg.subtitle)}</p><h1>${esc(seg.name)}</h1></div></header><div class="map-task" id="map-task"></div><div class="explore-bottom"><span>点击地面 / WASD 移动 · E 互动</span><button id="interact" class="primary" hidden></button></div><div class="map-loader" id="map-loader">正在铺开地图…</div><div class="touch-direction"><button data-move="up" aria-label="向上移动">↑</button><div><button data-move="left" aria-label="向左移动">←</button><button data-move="down" aria-label="向下移动">↓</button><button data-move="right" aria-label="向右移动">→</button></div></div></section><aside id="explore-panel" class="explore-panel"></aside></main>`;
 const panel=$('#explore-panel',root),container=$('#explore-canvas',root);bind('#explore-home',()=>{if(busy){toast('请等这次交谈保存完成。');return;}home();},root);
 const missing=()=>seg.points.filter(p=>p.required&&!collected.includes(p.id));
 const taskDone=()=>!seg.task||data.games[seg.id+':'+seg.task]!==undefined;
 const canExit=()=>seg.id==='E6'?!!session?.clues.some(c=>c.id==='refusal')&&!!session?.clues.some(c=>c.id==='intervention')&&collected.includes('crossquestion')&&taskDone():missing().length===0&&taskDone();
 const changed=()=>{lastProgress=Date.now();hintLevel=0;save();counter();scene?.refreshLabels();};
 function counter(){const n=$('#map-task',root);if(!n)return;n.textContent=seg.id==='E6'?`已收集 ${session?.clues.length??0} 条证词 · ${collected.includes('crossquestion')?'已携证追问':'等待携证追问'}`:`已完成 ${collected.filter(id=>seg.points.some(p=>p.id===id&&p.required)).length} / ${seg.points.filter(p=>p.required).length} 项观察`;}
 function addNote(id:string,n:Omit<Note,'id'>){if(!data.notes.some(x=>x.id===id))data.notes.push({id,...n});}
 function completePoint(p:Hotspot){if(!collected.includes(p.id))collected.push(p.id);if(p.note)addNote(seg.id+':'+p.id,p.note);changed();}
 function renderHome(){if(disposed)return;view='home';active=null;counter();panel.innerHTML=`<header class="explore-panel-head"><div><p class="eyebrow">${seg.id==='E6'?'一场未平的争执':'华浅的行旅'}</p><h2>${esc(seg.name)}</h2></div><span class="seal">探</span></header><div class="explore-portrait"><img src="${character('char-huaqian',seg.id==='E5'?'男装':'思')}" alt="华浅原人物立绘"></div><p class="explore-intro">${esc(seg.intro)}</p><div class="point-list">${seg.points.map(p=>`<button data-point="${p.id}"><span>${collected.includes(p.id)?'✓':p.npc?'◇':p.required?'○':'·'}</span><strong>${esc(p.name)}</strong><small>${p.npc?'交谈':p.required?'目标':'可选'}</small></button>`).join('')}</div><footer class="explore-actions"><button id="explore-notes">手记 ${data.notes.length}</button><button id="exit-explore" class="primary">${seg.id==='E6'?'理清证词':'继续故事'} →</button><p>自动保存 · ${seg.id==='E6'?(mode==='ai'?'实时 AI / 可切换预设':'预设问答'):'自由探索'}</p></footer>`;seg.points.forEach(p=>bind(`[data-point="${p.id}"]`,()=>scene.pick(p),panel));bind('#explore-notes',renderNotes,panel);bind('#exit-explore',tryFinish,panel);}
 function showPoint(p:Hotspot){if(disposed)return;active=p;if(p.npc){view='chat';void openChat(p);return;}view='point';panel.innerHTML=`<header class="explore-panel-head"><div><p class="eyebrow">${p.required?'目标观察':'途中一见'}</p><h2>${esc(p.name)}</h2></div><button id="close-point">返回</button></header>${p.character&&character(p.character)?`<div class="explore-portrait"><img src="${character(p.character)}" alt="${esc(p.name)}"></div>`:'<div class="observation-mark">◇</div>'}<p class="point-reading">${esc(p.text)}</p>${p.mini&&!collected.includes(p.id)?`<button id="point-mini" class="primary">${p.mini.startsWith('accounts')?'核对账目':p.mini==='medicine'?'度过这一日':'试一试'}</button>`:`<button id="point-collect" class="primary">${collected.includes(p.id)?'已记下 · 返回探索':'记在手记里'}</button>`}<p class="subtle">${p.note?'观察会连同来源一并保存。':'人物的话只代表眼前情境。'}</p>`;bind('#close-point',renderHome,panel);bind('#point-collect',()=>{completePoint(p);renderHome();toast(p.note?'手记已更新：'+p.note.title:'已记下这处观察。');},panel);bind('#point-mini',()=>runMini(p.mini!,score=>{data.games[p.mini!]=Math.max(data.games[p.mini!]??0,score);completePoint(p);renderHome();}),panel);}
 function runMini(id:string,done:(score:number)=>void){view='mini';scene.stop();const layer=document.createElement('div');layer.className='minigame-overlay';root.append(layer);miniCleanup=launchMiniGame(layer,id,score=>{miniCleanup?.();miniCleanup=undefined;layer.remove();done(score);});}
 function renderNotes(){view='notes';panel.innerHTML=`<header class="explore-panel-head"><div><p class="eyebrow">所见 · 所闻 · 所思</p><h2>华浅手记</h2></div><button id="close-notes">返回</button></header><div class="investigation-progress">${seg.id==='E6'?`<span class="${session?.clues.some(c=>c.id==='refusal')?'done':''}">听当事人</span><span class="${session?.clues.some(c=>c.id==='intervention')?'done':''}">问出手者</span><span class="${collected.includes('crossquestion')?'done':''}">携证追问</span>`:''}</div><div class="scroll-notes">${data.notes.map(n=>`<article class="note-card"><small>${esc(n.kind)} · ${esc(n.source)}</small><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p>${n.question?`<a href="https://www.zhihu.com/search?type=content&q=${encodeURIComponent(n.question)}" target="_blank" rel="noopener">在知乎继续讨论 ↗</a>`:''}</article>`).join('')||'<p class="empty">还未收集到新的观察。</p>'}</div><button id="copy-notes">导出我的手记</button>`;bind('#close-notes',renderHome,panel);bind('#copy-notes',()=>download('华浅-探索手记.md',data.notes.map(n=>`## ${n.title}\n\n${n.text}\n\n来源：${n.source}（${n.kind}）`).join('\n\n'),'text/markdown'),panel);}
 function tryFinish(){if(busy)return;if(seg.id==='E6'){if(!session?.clues.some(c=>c.id==='refusal')){toast('先听琵琶女说清自己的意愿。');scene.pick(seg.points.find(p=>p.id==='pipa')!);return;}if(!session.clues.some(c=>c.id==='intervention')){toast('再问问江湖人为何出手。');scene.pick(seg.points.find(p=>p.id==='blue')!);return;}if(!collected.includes('crossquestion')){toast('带着姑娘的证词，向华深再问一句。');scene.pick(seg.points.find(p=>p.id==='huashen')!);return;}}
  if(missing().length){toast('还需要看看：'+missing().map(p=>p.name).join('、'));scene.pick(missing()[0]);return;}
  if(!taskDone()){runMini(seg.task!,score=>{data.games[seg.id+':'+seg.task]=score;changed();renderHome();tryFinish();});return;}
  view='finish';panel.innerHTML=`<header class="explore-panel-head"><div><p class="eyebrow">这一程的收获</p><h2>${seg.id==='E6'?'证词已经串起':'可以继续了'}</h2></div><span class="seal">记</span></header><p class="point-reading">${seg.id==='E6'?'姑娘明确表达不愿意；两名江湖人解释了出手缘由；华深仍想让妹妹撑腰。听到的说法应保留来源，最后如何出面，交还给故事中的华浅。':esc(seg.exit)}</p><div class="note-card"><h3>${seg.id==='E6'?'从听说走向核对':'把这一程留在手记里'}</h3><p>${seg.id==='E6'?'证词冲突已经追问。人物态度与确凿事实分别保存；没有证据的隐情仍待核实。':'探索中的观察已经保存，接下来回到原卷一剧情。'}</p></div><button id="confirm-finish" class="primary">${esc(seg.exit)} →</button><button id="stay-explore" class="text-link">再看看</button>`;bind('#confirm-finish',()=>{if(canExit())finish();},panel);bind('#stay-explore',renderHome,panel);
 }
 async function api<T>(url:string,body?:unknown):Promise<T>{const r=await fetch(BASE+'api/'+url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(55000)});const d=await r.json();if(!r.ok)throw Error(d.message??'暂时无法回应，请稍后重试。');return d;}
 async function getSession(){if(session)return;if(sessionPromise)return sessionPromise;sessionPromise=(async()=>{try{if(data.session)session=await api<SessionView>('sessions/'+data.session);}catch{}if(!session){session=await api<SessionView>('sessions',{});data.session=session.id;save();}syncClues();})();try{await sessionPromise;}finally{sessionPromise=null;}}
 function syncClues(){if(!session)return;for(const c of session.clues)addNote('tavern:'+c.id,{title:c.title,text:c.detail,source:c.source,kind:c.kind==='人物立场'?'推断':'证词'});changed();}
 async function openChat(p:Hotspot){renderChat(p,'正在找回交谈记录…');try{await getSession();if(!disposed&&active?.id===p.id)renderChat(p);}catch(e){if(!disposed&&active?.id===p.id)renderChat(p,e instanceof Error?e.message:'无法连接。');}}
 function renderChat(p:Hotspot,error=''){view='chat';const id=p.npc!;const turns=session?.history[id]??[];panel.innerHTML=`<header class="explore-panel-head"><div><p class="eyebrow">${mode==='ai'?'实时 AI 交谈':'预设问答'}</p><h2>${esc(p.name)}</h2></div><button id="close-chat" ${busy?'disabled':''}>返回</button></header><div class="chat-portrait">${character(p.character!)?`<img src="${character(p.character!)}" alt="${esc(p.name)}">`:'<div class="observation-mark">◇</div>'}<span>${({calm:'平静',guarded:'谨慎',angry:'不悦',relieved:'缓和'} as any)[session?.emotions[id]??'calm']}</span></div><div id="chat-log" class="chat-log" role="log">${turns.length?turns.map(t=>`<article class="chat-turn ${t.role}"><small>${t.role==='user'?'华浅':esc(p.name)}${t.source==='preset'?' · 预设台词':''}${t.guarded?' · 回应已收束':''}</small><p>${esc(t.content)}</p></article>`).join(''):`<article class="chat-turn"><p>${esc(p.text)}</p></article>`}${busy?'<p class="typing">对方正在回应…</p>':''}</div><form id="npc-form" class="npc-form"><div class="chat-suggestions">${(NPCS.find(n=>n.id===id)?.prompts??[]).map(q=>`<button type="button" data-question="${esc(q)}" ${busy?'disabled':''}>${esc(q)}</button>`).join('')}</div><label class="evidence-select">出示证词<select id="evidence" ${busy?'disabled':''}><option value="">不出示</option>${(session?.clues??[]).map(c=>`<option value="${c.id}" ${id==='huashen'&&c.id==='refusal'?'selected':''}>${esc(c.source)}：${esc(c.title)}</option>`).join('')}</select></label><textarea id="npc-question" maxlength="500" rows="2" placeholder="写下你想问的话…" ${busy?'disabled':''}>${pendingRequest?.npc===id?esc(pendingRequest.question):''}</textarea><div class="npc-form-bottom"><select id="npc-mode" aria-label="对话方式" ${busy?'disabled':''}><option value="ai" ${mode==='ai'?'selected':''}>实时 AI</option><option value="preset" ${mode==='preset'?'selected':''}>预设问答</option></select><button class="primary" ${busy?'disabled':''}>${busy?'回应中…':'询问 →'}</button></div>${error?`<p class="inline-error" role="alert">${esc(error)}</p>`:''}<small>Enter 询问 · 证词按来源保留</small></form>`;
 bind('#close-chat',renderHome,panel);panel.querySelectorAll<HTMLButtonElement>('[data-question]').forEach(b=>b.onclick=()=>{$<HTMLTextAreaElement>('#npc-question',panel).value=b.dataset.question!;});$<HTMLSelectElement>('#npc-mode',panel).onchange=e=>{mode=(e.target as HTMLSelectElement).value as 'ai'|'preset';};const form=$<HTMLFormElement>('#npc-form',panel);form.onsubmit=e=>{e.preventDefault();void send(p);};$<HTMLTextAreaElement>('#npc-question',panel).onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();void send(p);}};$('#chat-log',panel).scrollTop=$('#chat-log',panel).scrollHeight;
 }
 async function send(p:Hotspot){if(busy)return;const q=$<HTMLTextAreaElement>('#npc-question',panel).value.trim();if(!q){toast('先写一句想问的话。');return;}const evidenceId=$<HTMLSelectElement>('#evidence',panel).value||undefined;const id=p.npc!;if(!pendingRequest||pendingRequest.question!==q||pendingRequest.npc!==id||pendingRequest.mode!==mode||pendingRequest.evidenceId!==evidenceId)pendingRequest={id:crypto.randomUUID(),npc:id,question:q,mode,evidenceId};busy=true;renderChat(p);try{await getSession();const r=await api<DialogueResult>('talk',{sessionId:session!.id,requestId:pendingRequest.id,npcId:id,question:q,mode,evidenceId,position:{...scene.pos}});if(disposed)return;session=r.session;pendingRequest=null;syncClues();if(!collected.includes(p.id))collected.push(p.id);if(id==='huashen'&&evidenceId==='refusal'){if(!collected.includes('crossquestion'))collected.push('crossquestion');addNote('tavern:crossquestion',{title:'已携证追问兄长',text:'把琵琶女不情愿的陈述当面出示给华深。记录保留了这次追问及回应，并未把人物口头辩解当作已证实事实。',source:'华浅的追问记录',kind:'观察'});}changed();busy=false;renderChat(p);if(r.newClues.length)toast('手记已更新：'+r.newClues.map(c=>c.title).join('、'));}catch(e){busy=false;if(!disposed)renderChat(p,e instanceof Error?e.message:'连接中断。可以切换预设问答后重试。');}}
 class MapScene extends Phaser.Scene{
  pos={...(data.positions[seg.id]??seg.entry)};hero!:Phaser.GameObjects.Image;shadow!:Phaser.GameObjects.Ellipse;name!:Phaser.GameObjects.Text;route:Point[]=[];target:Hotspot|null=null;keys=new Set<string>();labels=new Map<string,Phaser.GameObjects.Text>();clock=0;saveClock=0;keyDown!:(e:KeyboardEvent)=>void;keyUp!:(e:KeyboardEvent)=>void;
  constructor(){super('exploration-'+seg.id);if(!walkable(seg.map,this.pos))this.pos={...seg.entry};}
  preload(){this.load.image('map',BASE+'media/map-'+seg.map+'.webp');this.load.image('hero',character('char-huaqian',seg.id==='E5'?'男装':'思'));for(const p of seg.points)if(p.character&&character(p.character))this.load.image(p.id,character(p.character));this.load.on('loaderror',()=>toast('有素材暂未载入，可刷新恢复进度。'));}
  create(){this.add.image(0,0,'map').setOrigin(0).setDisplaySize(1254,1254);for(const p of seg.points){if(p.character&&this.textures.exists(p.id)){this.add.ellipse(p.x,p.y,44,14,0x263930,.25);this.add.image(p.x,p.y,p.id).setOrigin(.5,1).setDisplaySize(79,120).setDepth(p.y);}else this.add.circle(p.x,p.y,10,0xe6d7a6,.6).setStrokeStyle(2,0xffffff,.7);const label=this.add.text(p.x,p.y-(p.character?132:32),p.name,{fontFamily:'Songti SC,serif',fontSize:'19px',resolution:2,color:'#fff8e7',backgroundColor:'#324f47',padding:{x:10,y:5}}).setOrigin(.5).setDepth(1500).setInteractive({useHandCursor:true}).on('pointerdown',()=>{if(view==='home')this.pick(p);});this.labels.set(p.id,label);}
   this.shadow=this.add.ellipse(this.pos.x,this.pos.y,50,17,0x658471,.34).setStrokeStyle(2,0xefe7ba);this.hero=this.add.image(this.pos.x,this.pos.y,'hero').setOrigin(.5,1).setDisplaySize(81,123);this.name=this.add.text(this.pos.x,this.pos.y-140,'华浅',{fontFamily:'Songti SC,serif',fontSize:'19px',resolution:2,color:'#fff8e7',backgroundColor:'#5c7762',padding:{x:8,y:4}}).setOrigin(.5).setDepth(1600);this.resize();this.scale.on('resize',()=>this.resize());this.input.on('pointerdown',(pointer:Phaser.Input.Pointer,over:unknown[])=>{if(view!=='home'||over.length)return;const t=this.cameras.main.getWorldPoint(pointer.x,pointer.y);const r=pathTo(seg.map,this.pos,t);if(r){this.route=r;this.target=null;}else toast('这里有陈设或水面，试试点空地。');});
   this.keyDown=e=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement||e.target instanceof HTMLSelectElement)return;const k=e.key.toLowerCase();if(view==='home'&&['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){e.preventDefault();this.keys.add(k);this.route=[];this.target=null;}if(view==='home'&&k==='e'&&!e.repeat&&near)showPoint(near);};this.keyUp=e=>this.keys.delete(e.key.toLowerCase());window.addEventListener('keydown',this.keyDown);window.addEventListener('keyup',this.keyUp);window.addEventListener('blur',this.blur);this.events.once('shutdown',()=>{window.removeEventListener('keydown',this.keyDown);window.removeEventListener('keyup',this.keyUp);window.removeEventListener('blur',this.blur);});$('#map-loader',root)?.remove();ready=true;this.refreshLabels();}
  blur=()=>this.stop();
  stop(){this.keys.clear();this.route=[];this.target=null;}
  refreshLabels(){for(const p of seg.points){const l=this.labels.get(p.id);l?.setText((collected.includes(p.id)?'✓ ':'')+p.name);l?.setAlpha(collected.includes(p.id)?.72:1);}}
  resize(){const dpr=Math.min(devicePixelRatio||1,2),w=container.clientWidth,h=container.clientHeight;this.cameras.main.setBounds(0,0,1254,1254).setZoom(Math.min(w/880,h/880)*dpr).centerOn(this.pos.x,this.pos.y-100);}
  pick(p:Hotspot){if(view!=='home'||!ready)return;if(Math.hypot(this.pos.x-p.x,this.pos.y-p.y)<=135){showPoint(p);return;}const r=approach(seg.map,this.pos,p);if(r){this.route=r;this.target=p;toast('前往'+p.name+'附近。');}else toast('先从旁边的空地绕过去。');}
  update(_t:number,delta:number){if(!this.hero||disposed)return;const dt=Math.min(delta,50)/1000;let dx=0,dy=0;if(view==='home'){dx=Number(this.keys.has('d')||this.keys.has('arrowright'))-Number(this.keys.has('a')||this.keys.has('arrowleft'));dy=Number(this.keys.has('s')||this.keys.has('arrowdown'))-Number(this.keys.has('w')||this.keys.has('arrowup'));if(!dx&&!dy&&this.route.length){const t=this.route[0],dist=Math.hypot(t.x-this.pos.x,t.y-this.pos.y);if(dist<7){this.route.shift();if(!this.route.length&&this.target){const p=this.target;this.target=null;if(Math.hypot(this.pos.x-p.x,this.pos.y-p.y)<=138)showPoint(p);}}else{dx=(t.x-this.pos.x)/dist;dy=(t.y-this.pos.y)/dist;}}if(dx||dy){const length=Math.hypot(dx,dy);dx=dx/Math.max(1,length)*215*dt;dy=dy/Math.max(1,length)*215*dt;for(let i=0;i<4;i++){if(walkable(seg.map,{x:this.pos.x+dx/4,y:this.pos.y}))this.pos.x+=dx/4;if(walkable(seg.map,{x:this.pos.x,y:this.pos.y+dy/4}))this.pos.y+=dy/4;}}}
   this.clock+=dt;this.hero.setPosition(this.pos.x,this.pos.y+((dx||dy)?Math.sin(this.clock*13)*2:0)).setDepth(this.pos.y);this.shadow.setPosition(this.pos.x,this.pos.y).setDepth(this.pos.y-1);this.name.setPosition(this.pos.x,this.pos.y-140);this.cameras.main.centerOn(this.pos.x,this.pos.y-105);near=seg.points.filter(p=>Math.hypot(this.pos.x-p.x,this.pos.y-p.y)<135).sort((a,b)=>Math.hypot(this.pos.x-a.x,this.pos.y-a.y)-Math.hypot(this.pos.x-b.x,this.pos.y-b.y))[0]??null;const btn=$<HTMLButtonElement>('#interact',root);if(btn){btn.hidden=!near||view!=='home';btn.textContent=near?'E · '+near.name:'';}this.saveClock+=dt;if(this.saveClock>1){this.saveClock=0;data.positions[seg.id]={...this.pos};save();}
  }
 }
 const scene=new MapScene();const dpr=Math.min(devicePixelRatio||1,2);const game=new Phaser.Game({type:Phaser.AUTO,parent:container,width:container.clientWidth*dpr,height:container.clientHeight*dpr,backgroundColor:'#3b463b',antialias:true,pixelArt:false,scale:{mode:Phaser.Scale.NONE,zoom:1/dpr},scene:[scene],audio:{noAudio:true},input:{activePointers:3}});
 const observer=new ResizeObserver(()=>{if(disposed)return;const d=Math.min(devicePixelRatio||1,2);game.scale.setZoom(1/d);game.scale.resize(container.clientWidth*d,container.clientHeight*d);});observer.observe(container);bind('#interact',()=>{if(near&&view==='home')showPoint(near);},root);
 const keys:Record<string,string>={up:'w',down:'s',left:'a',right:'d'};root.querySelectorAll<HTMLButtonElement>('[data-move]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();if(view!=='home')return;b.setPointerCapture(e.pointerId);scene.route=[];scene.keys.add(keys[b.dataset.move!]);};const up=()=>scene.keys.delete(keys[b.dataset.move!]);b.onpointerup=up;b.onpointercancel=up;b.onlostpointercapture=up;});
 const hints=window.setInterval(()=>{if(disposed||view!=='home')return;const idle=Date.now()-lastProgress;const level=idle>180000?3:idle>120000?2:idle>60000?1:0;if(level>hintLevel){hintLevel=level;const target=missing()[0]??seg.points.find(p=>!collected.includes(p.id));if(target){toast(level===1?'可以点右侧列表，前往还没看过的地方。':level===2?'千芷提醒：不妨先去看看'+target.name+'。':'目标已标记：'+target.name);scene.labels.get(target.id)?.setBackgroundColor('#966b32');if(level===3)scene.pick(target);}}},4000);
 renderHome();if(seg.id==='E6')void getSession().then(()=>{if(!disposed&&view==='home')renderHome();}).catch(()=>toast('实时交谈暂未连接，稍后可重试。'));
 return ()=>{if(disposed)return;disposed=true;clearInterval(hints);miniCleanup?.();observer.disconnect();data.positions[seg.id]={...scene.pos};game.destroy(true);};
}
