import './style.css';
import {showZhihuAccount} from './zhihu';
import {StoryEngine,blockText,CHAPTER_NAMES,type Block} from './story-engine';
import {initialize,catalog,BASE,asset,art,character,esc,$,bind,toast,profile,persist,emptyExploration,type Save,type ExplorationState,speaker,audio,playMusic,stopVoice,playVoice,playSound,syncAudio,download,currentMusic,restoreMusic} from './core';
import {segments,segmentForBlock} from './segments';
import {launchExploration} from './exploration';
import {showGameHub} from './minigames';
const app=$('#app');
let story:StoryEngine;let bg='';let lastPortrait='';let lastSlot='right';let state='loading';let exploration:ExplorationState=emptyExploration();let activeExplore='';let history:Save['history']=[];let review=false;let typeTimer=0;let autoTimer=0;let auto=false;let skip=false;let fullText='';let typed=0;let transitionTimer=0;let transitionDone:(()=>void)|null=null;let disposeExplore:(()=>void)|null=null;let uiReturn:(()=>void)|null=null;let epoch=0;
app.innerHTML='<div class="loading-page"><div class="seal">华</div><h1>洗铅华</h1><p>正在展开这一卷故事…</p></div>';
function clearTimers(){window.clearInterval(typeTimer);window.clearTimeout(autoTimer);window.clearTimeout(transitionTimer);typeTimer=autoTimer=transitionTimer=0;}
function resetView(){clearTimers();disposeExplore?.();disposeExplore=null;epoch++;stopVoice();}
function snapshot():Save{return {version:1,at:Date.now(),story:story.snapshot(),bg,lastPortrait,lastSlot,history:history.slice(-600),exploration:structuredClone(exploration),activeExplore,review,musicPath:currentMusic()};}
function saveAuto(){if(!story)return;if(review)profile.reviewAuto=snapshot();else profile.auto=snapshot();persist();}
function title(){resetView();state='title';activeExplore='';uiReturn=null;auto=skip=false;audio.ambient.pause();playMusic('bgm/bgm-title-xiqianhua.mp3');
 app.innerHTML=`<main class="title-screen" style="--title-bg:url('${art('userref-final/provided/provided-cover-background.png')}')"><div class="title-mist"></div><div class="title-copy"><h1 class="sr-only">洗铅华 · 卷一</h1><p class="title-poem">故事的结局，藏在每一次选择里。<br>这一次，亲自走进她的世界。</p></div><nav class="title-menu" aria-label="主菜单"><button id="start" class="ornate primary-menu">初入书中 <span>开始故事</span></button><button id="continue" class="ornate" ${profile.auto?'':'disabled'}>续写前缘 <span>继续游戏</span></button><button id="review" class="ornate">入局一览 <span>快速体验</span></button><div class="menu-pair"><button id="chapters">章节</button><button id="saves">存档</button><button id="gallery">收藏</button><button id="games">游艺</button><button id="settings">设置</button><button id="about">关于</button></div></nav><footer class="title-footer"><span>视觉小说 × 2D 探索 × AI 人物</span><span>建议横屏 · 耳机体验</span></footer></main>`;
 bind('#start',()=>{if(profile.auto)modal('开启新的故事','自动进度会从序幕重新记录。你保存的手动存档仍可在「存档」中读取。',[['开始新故事',newGame],['先回去',title]]);else newGame();});bind('#continue',()=>restore(profile.auto!));bind('#review',()=>chapters(true));bind('#chapters',()=>chapters());bind('#saves',()=>saves());bind('#gallery',()=>gallery());bind('#games',()=>{resetView();state='games';showGameHub(app,title);});bind('#settings',settings);bind('#about',about);
}
function newGame(){resetView();story.start();bg='';lastPortrait='';lastSlot='right';exploration=emptyExploration();history=[];review=false;activeExplore='';auto=skip=false;startOpening(()=>advance(true));}
function startOpening(done:()=>void){state='op';const e=++epoch;app.innerHTML=`<div class="opening"><video id="opening-video" src="${BASE}media/opening.mp4" playsinline autoplay></video><button id="skip-op" class="glass">跳过片头 →</button></div>`;const v=$<HTMLVideoElement>('#opening-video');v.volume=profile.settings.volume*.7;audio.music.pause();audio.ambient.pause();let ended=false;const finish=()=>{if(ended||e!==epoch)return;ended=true;v.pause();done();};v.onended=finish;v.onerror=finish;bind('#skip-op',finish);v.play().catch(()=>{v.controls=true;});}
function modal(name:string,text:string,actions:[string,()=>void][]){resetView();state='modal';app.innerHTML=`<div class="paper-page centered"><section class="paper-card"><p class="eyebrow">洗铅华 · 卷一</p><h1>${esc(name)}</h1><p>${esc(text)}</p><div class="modal-actions">${actions.map(([label],i)=>`<button data-action="${i}" class="${i===0?'primary':''}">${esc(label)}</button>`).join('')}</div></section></div>`;actions.forEach(([,fn],i)=>bind(`[data-action="${i}"]`,fn));}
function transition(from:string,to:string,next:()=>void){const path=catalog.transitions[`${from}>${to}`];const u=asset(path??'');if(!u){next();return;}clearTimers();state='transition';stopVoice();transitionDone=next;app.innerHTML=`<button class="transition-screen" id="transition" aria-label="跳过转场"><img src="${u}" alt="${esc(CHAPTER_NAMES[to]??'时光流转')}"><span>点击任意处继续</span></button>`;const finish=()=>{clearTimeout(transitionTimer);const fn=transitionDone;transitionDone=null;fn?.();};bind('#transition',finish);transitionTimer=window.setTimeout(finish,4000);}
function advance(first=false){if(state==='explore')return;clearTimers();stopVoice();let before=first?'__new_game__':story.fragment;
 try{for(let n=0;n<500;n++){const b=story.next();if(!profile.visited.includes(story.fragment))profile.visited.push(story.fragment);if(story.fragment.startsWith('end-')&&!profile.endings.includes(story.fragment))profile.endings.push(story.fragment);
  if(b.type==='scene'){const p=b.props;const scene=catalog.scenes.find(s=>s.id===p.sceneId);bg=p.backgroundPath??p.background??scene?.layers[0]?.assetPath??bg;if(String(p.autoAddToGallery)==='true'&&!profile.unlocked.includes(bg))profile.unlocked.push(bg);continue;}
  if(b.type==='sound'){playSound(b);continue;}
  if(b.type==='callExtensionFunction'){try{const p=JSON.parse(b.props.paramsJson??'{}');if(p.audio&&!profile.unlocked.includes(p.audio))profile.unlocked.push(p.audio);}catch{}continue;}
  if(b.type==='returnToEntry'){modal('卷一 · 暂告一段落','此间风雨未歇，属于华浅的故事仍在继续。你已走完当前卷的主线。',[['查看收藏',()=>gallery()],['回到首页',title]]);return;}
  if(!['dialogue','narration','floatingText','branch'].includes(b.type))continue;
  const perform=()=>{const seg=segmentForBlock(story.fragment,b.id,story.variables);if(seg&&!exploration.done.includes(seg.id)){activeExplore=seg.id;saveAuto();explore(seg.id);}else{const inline=({'s2-07-b008':'memorial','s2-09-b018':'noodles'} as Record<string,string>)[b.id];if(inline&&exploration.games['inline:'+b.id]===undefined){showInlineGame(inline,()=>{exploration.games['inline:'+b.id]=exploration.games[inline]??0;saveAuto();renderBlock(true);});}else renderBlock(true);}};
  if(before!==story.fragment){transition(before,story.fragment,perform);}else perform();return;
 }}catch(err){modal('这页暂时无法展开',err instanceof Error?err.message:'读取中断',[['读取自动进度',()=>{if(profile.auto)restore(profile.auto);else title();}],['回到首页',title]]);}}
function portraitFor(b:Block){const p=b.props;const isCG=/\bcg[/-]/.test(bg);if(isCG||b.id==='s1-00-veil-b010')return '';if(b.type==='narration'&&blockText(b).includes('我'))return '';if(b.type==='dialogue'&&p.characterId!=='char-huaqian'){let path=p.portraitPath??p.portrait??'';if(!path){const ch=catalog.characters.find(c=>c.id===p.characterId);path=ch?.expressions.find(e=>e.name===p.expression)?.assetPath??ch?.expressions.find(e=>e.name==='微笑')?.assetPath??ch?.expressions[0]?.assetPath??'';}if(path&&asset(path)){lastPortrait=path;lastSlot=p.position??'right';}else if(p.showCharacter===false&&p.keepCharacter===false&&/司礼|宾客|门外/.test(p.characterName??'')){lastPortrait='';}}
 if(lastPortrait.includes('/char-huaqian/'))lastPortrait='';return asset(lastPortrait);}
function renderBlock(record=false){clearTimers();state='vn';activeExplore='';const b=story.current;if(!b){advance();return;}const portrait=portraitFor(b);const text=blockText(b);fullText=b.type==='dialogue'&&!/^[“「『"]/.test(text)?`“${text}”`:text;const who=speaker(b);const wasRead=profile.seen.includes(b.id);if(record&&b.type!=='branch'&&history.at(-1)?.block!==b.id){history.push({speaker:who,text:fullText,block:b.id});if(history.length>600)history.shift();}if(!profile.seen.includes(b.id))profile.seen.push(b.id);saveAuto();
 app.innerHTML=`<main class="vn-screen"><div class="vn-stage" style="--scene:url('${asset(bg)}')"><img class="scene-image" src="${asset(bg)}" alt="当前剧情场景"><div class="scene-light"></div>${portrait?`<img class="vn-character slot-${esc(lastSlot)}" src="${portrait}" alt="${esc(who)}的立绘">`:''}<header class="vn-header"><button id="home" class="glass">‹ 首页</button><span>${esc(CHAPTER_NAMES[story.fragment]??'洗铅华 · 卷一')}${review?' · 快速体验':''}</span><button id="notebook" class="glass">手记 ${exploration.notes.length||''}</button></header>${b.type==='branch'?`<section class="choices"><p class="eyebrow">一念之间</p><h2>${esc(b.props.title)}</h2>${story.choices().map((o,i)=>`<button data-choice="${i}"><span class="choice-number">${['壹','贰','叁','肆'][i]}</span><span>${esc(o.text)}</span></button>`).join('')}</section>`:`<section class="dialogue" aria-label="剧情对白"><nav class="dialogue-tools"><button id="history">履历</button><button id="auto" class="${auto?'active':''}">自动</button><button id="skip" class="${skip?'active':''}">快进</button><button id="save">保存</button><button id="load">读档</button><button id="setting">设置</button><button id="hide">隐藏</button></nav><div class="dialogue-frame"><div class="speaker-name">${esc(who)}</div><p id="dialogue-text" class="dialogue-text ${fullText.length>95?'long':''}"></p><button id="next" class="next-cue" aria-label="下一句">继续 <span>◆</span></button></div></section>`}</div></main>`;
 document.querySelectorAll<HTMLImageElement>('.vn-character').forEach(i=>i.onerror=()=>{i.hidden=true;});bind('#home',()=>{saveAuto();title();});bind('#notebook',notes);bind('#history',showHistory);bind('#save',()=>saves('save'));bind('#load',()=>saves('load'));bind('#setting',settings);bind('#auto',()=>{auto=!auto;skip=false;renderBlock();});bind('#skip',()=>{skip=!skip;auto=false;renderBlock();});bind('#hide',()=>{const d=$('.dialogue');d.hidden=true;$('.vn-stage').onclick=()=>{d.hidden=false;$('.vn-stage').onclick=null;};});
 if(b.type==='branch'){story.choices().forEach((o,i)=>bind(`[data-choice="${i}"]`,()=>{const before=story.fragment;story.choose(i);lastPortrait='';const continueChoice=()=>advance();const mini=before==='s1-04'&&o.fragmentId==='opt-choice-pond-swim';if(mini){showInlineGame('swim',continueChoice);}else transition(before,story.fragment,continueChoice);}));return;}
 bind('#next',nextText);const t=$('#dialogue-text');typed=profile.settings.instant?fullText.length:0;t.textContent=fullText.slice(0,typed);if(typed<fullText.length)typeTimer=window.setInterval(()=>{typed=Math.min(fullText.length,typed+1);t.textContent=fullText.slice(0,typed);if(typed===fullText.length){clearInterval(typeTimer);scheduleAuto(wasRead);}},1000/profile.settings.speed);else scheduleAuto(wasRead);playVoice(b);
}
function scheduleAuto(wasRead:boolean){if(skip&&wasRead){autoTimer=window.setTimeout(()=>advance(),180);return;}if(skip&&!wasRead){skip=false;$('#skip')?.classList.remove('active');toast('已停在未读内容。');}if(auto){const wait=()=>{if(state!=='vn'||!auto)return;if(!audio.voice.paused&&!audio.voice.ended){autoTimer=window.setTimeout(wait,500);return;}autoTimer=window.setTimeout(()=>advance(),Math.max(1800,fullText.length*40));};wait();}}
function nextText(){if(state!=='vn'||story.current?.type==='branch')return;if(typed<fullText.length){clearInterval(typeTimer);typed=fullText.length;$('#dialogue-text').textContent=fullText;scheduleAuto(false);}else advance();}
function explore(id:string){resetView();state='explore';activeExplore=id;auto=skip=false;audio.ambient.pause();saveAuto();disposeExplore=launchExploration(app,segments.find(s=>s.id===id)!,exploration,()=>saveAuto(),()=>{disposeExplore?.();disposeExplore=null;if(!exploration.done.includes(id))exploration.done.push(id);activeExplore='';saveAuto();renderBlock(true);},()=>{saveAuto();title();});}
function restore(s:Save){try{if(s.version!==1)throw Error('存档版本不受支持');story.restore(s.story);if(!s.exploration||!Array.isArray(s.exploration.done)||!Array.isArray(s.exploration.notes))throw Error('探索存档不完整');resetView();bg=s.bg;lastPortrait=s.lastPortrait??'';lastSlot=s.lastSlot??'right';history=structuredClone(s.history??[]);exploration=structuredClone(s.exploration);review=!!s.review;restoreMusic(s.musicPath??'');activeExplore=s.activeExplore??'';auto=skip=false;if(activeExplore&&segments.some(x=>x.id===activeExplore))explore(activeExplore);else renderBlock();}catch(e){toast(e instanceof Error?e.message:'无法读取存档');title();}}
function returnFromPage(){const fn=uiReturn;uiReturn=null;if(fn)fn();else title();}
function page(name:string,body:string){const prior=state;if(prior==='vn')uiReturn=()=>renderBlock();else if(prior==='title')uiReturn=title;resetView();state='page';app.innerHTML=`<main class="paper-page"><header class="page-heading"><button id="back" class="text-link">‹ 返回</button><div><p class="eyebrow">洗铅华 · 卷一</p><h1>${esc(name)}</h1></div><span class="seal">华</span></header>${body}</main>`;bind('#back',returnFromPage);}
function saves(mode='load'){const current=state==='vn'?snapshot():null;page(mode==='save'?'留存此刻':'旧梦重续',`<p class="page-intro">六个手动位置。自动进度另行保存，导出文件可在另一台设备继续。</p><div class="save-grid">${Array.from({length:6},(_,i)=>{const s=profile.slots[i];return `<article class="save-slot">${s?.bg?`<img src="${asset(s.bg)}" alt="存档场景">`:''}<span class="slot-number">${String(i+1).padStart(2,'0')}</span><div><h3>${s?esc(CHAPTER_NAMES[s.story.fragment]??s.story.fragment):'尚未落笔'}</h3><p>${s?new Date(s.at).toLocaleString('zh-CN'):'保存一段属于你的故事'}</p><div class="inline-actions">${current?`<button data-write="${i}">${s?'覆盖此档':'保存在此'}</button>`:''}<button data-read="${i}" ${s?'':'disabled'}>读取</button></div></div></article>`;}).join('')}</div><div class="export-actions"><button id="export-save" ${profile.auto?'':'disabled'}>导出当前进度</button><label class="file-button">导入进度<input id="import-save" type="file" accept=".json"></label><button id="auto-load" ${profile.auto?'':'disabled'}>读取自动进度</button></div>`);
 for(let i=0;i<6;i++){bind(`[data-write="${i}"]`,()=>{if(!current)return;const doWrite=()=>{profile.slots[i]=current;persist();toast('已保存到位置 '+(i+1));renderBlock();};if(profile.slots[i])modal('覆盖这份存档？',CHAPTER_NAMES[profile.slots[i].story.fragment]??'现有存档',[['保存此刻',doWrite],['取消',()=>renderBlock()]]);else doWrite();});bind(`[data-read="${i}"]`,()=>restore(profile.slots[i]));}
 bind('#export-save',()=>download('洗铅华-存档.json',JSON.stringify(profile.auto,null,2)));bind('#auto-load',()=>restore(profile.auto!));$<HTMLInputElement>('#import-save').onchange=async e=>{const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;if(f.size>2000000){toast('文件过大，请选择游戏导出的存档。');return;}try{restore(JSON.parse(await f.text()));}catch{toast('存档格式有误。');}};
}
function showHistory(){page('前尘履历',`<div class="history-list">${history.slice().reverse().map(t=>`<article><span>${esc(t.speaker)}</span><p>${esc(t.text)}</p></article>`).join('')||'<p>尚未展开故事。</p>'}</div>`);}
function notes(){page('华浅手记',`<p class="page-intro">把所见与所闻分开，结论才有来处。</p><div class="note-grid">${exploration.notes.map(n=>`<article class="note-card"><span class="eyebrow">${esc(n.kind)} · ${esc(n.source)}</span><h2>${esc(n.title)}</h2><p>${esc(n.text)}</p>${n.question?`<a href="https://www.zhihu.com/search?type=content&q=${encodeURIComponent(n.question)}" target="_blank" rel="noopener">去知乎继续讨论 ↗</a>`:''}</article>`).join('')||'<p class="empty">探索时获得的观察与证词会留在这里。</p>'}</div><button id="export-notes">导出我的手记</button>`);bind('#export-notes',()=>download('华浅手记.md','# 华浅手记\n\n'+exploration.notes.map(n=>`## ${n.title}\n\n${n.text}\n\n来源：${n.source}；类型：${n.kind}`).join('\n\n'),'text/markdown'));}
function settings(){page('方寸之间',`<section class="settings-card"><label>总音量 <input data-setting="volume" type="range" min="0" max="1" step=".05" value="${profile.settings.volume}"></label><label>音乐 <input data-setting="music" type="range" min="0" max="1" step=".05" value="${profile.settings.music}"></label><label>人物配音 <input data-setting="voice" type="range" min="0" max="1" step=".05" value="${profile.settings.voice}"></label><label>文字速度 <input data-setting="speed" type="range" min="15" max="80" step="1" value="${profile.settings.speed}"></label><label>文字一次显示 <input id="instant" type="checkbox" ${profile.settings.instant?'checked':''}></label><label>柔和动效 <input id="motion" type="checkbox" ${profile.settings.motion?'checked':''}></label><button id="fullscreen">切换全屏</button><p class="subtle">键盘：空格 / 回车继续，Esc 返回。探索中使用 WASD / 方向键，E 互动。手机可点击地面移动。</p></section>`);document.querySelectorAll<HTMLInputElement>('[data-setting]').forEach(i=>i.oninput=()=>{(profile.settings as any)[i.dataset.setting!]=Number(i.value);syncAudio();persist();});$<HTMLInputElement>('#instant').onchange=e=>{profile.settings.instant=(e.target as HTMLInputElement).checked;persist();};$<HTMLInputElement>('#motion').onchange=e=>{profile.settings.motion=(e.target as HTMLInputElement).checked;document.documentElement.classList.toggle('reduced-motion',!profile.settings.motion);persist();};bind('#fullscreen',()=>{if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen().catch(()=>toast('可使用浏览器的全屏功能。'));});}
function gallery(category='cg'){const cg=profile.unlocked.filter(p=>p.includes('cg/'));const mus=profile.unlocked.filter(p=>/\.(mp3|ogg|wav)$/.test(p));page('浮生藏卷',`<nav class="tabs"><button data-tab="cg" class="${category==='cg'?'active':''}">画卷 ${cg.length}</button><button data-tab="music" class="${category==='music'?'active':''}">乐集 ${mus.length}</button><button data-tab="ending" class="${category==='ending'?'active':''}">结局 ${profile.endings.length}/6</button></nav>${category==='cg'?`<div class="gallery-grid">${cg.map((p,i)=>`<button data-cg="${i}"><img loading="lazy" src="${asset(p)}" alt="已解锁画卷 ${i+1}"><span>画卷 · ${String(i+1).padStart(2,'0')}</span></button>`).join('')||'<p class="empty">随故事推进，珍藏你亲历的画面。</p>'}</div>`:category==='music'?`<div class="music-list">${mus.map((p,i)=>`<button data-music="${i}"><span>▷</span> 乐章 ${String(i+1).padStart(2,'0')} <small>${esc(p.split('/').pop()?.replace(/\.[^.]+$/,''))}</small></button>`).join('')||'<p class="empty">读到相应场景后，音乐将收入乐集。</p>'}</div>`:`<div class="ending-grid">${Object.entries(CHAPTER_NAMES).filter(([id])=>id.startsWith('end-')).map(([id,n])=>`<article class="note-card ${profile.endings.includes(id)?'':'locked'}"><span class="seal">${profile.endings.includes(id)?'阅':'锁'}</span><h2>${profile.endings.includes(id)?n:'尚未抵达'}</h2><p>${profile.endings.includes(id)?'你曾走过这条路。':'每一个选择，都有它的余音。'}</p></article>`).join('')}</div>`}`);document.querySelectorAll<HTMLElement>('[data-tab]').forEach(b=>b.onclick=()=>gallery(b.dataset.tab));cg.forEach((p,i)=>bind(`[data-cg="${i}"]`,()=>{app.insertAdjacentHTML('beforeend',`<button id="lightbox" class="lightbox" aria-label="关闭画卷"><img src="${asset(p)}" alt="画卷全图"><span>点击关闭</span></button>`);bind('#lightbox',()=>$('#lightbox').remove());}));mus.forEach((p,i)=>bind(`[data-music="${i}"]`,()=>{playMusic(p);toast('正在播放乐章 '+(i+1));}));}
function jumpReview(id:string){resetView();review=true;story.start();bg='';lastPortrait='';exploration=emptyExploration();history=[];for(let n=0;n<4000;n++){if(story.fragment===id&&story.cursor===0)break;const b=story.next();if(story.fragment===id){story.cursor--;story.current=null;break;}if(b.type==='branch'){const opts=story.choices();const safe=opts.findIndex(o=>!o.fragmentId.startsWith('end-bad'));story.choose(Math.max(0,safe));}if(b.type==='returnToEntry')break;}if(story.fragment!==id)story.jump(id);advance();}
function chapters(isReview=false){page(isReview?'入局一览':'篇章目录',`<p class="page-intro">${isReview?'快速进入重点段落。体验进度单独记录，不覆盖完整故事的自动进度。':'已读篇章可回看，回看进度单独保存。未读章节随故事解锁。'}</p>${isReview?`<div class="review-cards"><button data-jump="s1-00-veil"><span>壹</span><h2>红盖头</h2><p>剧情演出与第一次选择</p></button><button data-jump="s1-09"><span>贰</span><h2>华府寻路</h2><p>自由探索与论据整理</p></button><button data-jump="s2-03"><span>叁</span><h2>酒楼风波</h2><p>AI 问询、来源手记与携证追问</p></button><button data-jump="s2-09"><span>肆</span><h2>生辰夜宴</h2><p>备宴、长寿面与卷末选择</p></button></div>`:`<div class="chapter-grid">${Object.entries(CHAPTER_NAMES).filter(([id])=>!id.startsWith('end-')).map(([id,n],i)=>`<button data-jump="${id}" ${profile.visited.includes(id)?'':'disabled'}><small>${String(i+1).padStart(2,'0')}</small><span>${profile.visited.includes(id)?esc(n):'尚未展开'}</span></button>`).join('')}</div>`}`);document.querySelectorAll<HTMLElement>('[data-jump]').forEach(b=>b.onclick=()=>jumpReview(b.dataset.jump!));}
function about(){page('此卷缘起',`<section class="about-copy"><h2>把阅读变成亲历</h2><p>《洗铅华 · 卷一》改编自七月荔《洗铅华》第 1—13 章。玩家以华浅的视角经历既定故事，在探索里寻找线索，在人物之间听取不同的说法。</p><p>主线与结局由剧本决定。AI 用于酒楼人物的即时交谈；线索由固定规则校验，AI 不能更改主线。AI 回应可能不准确，手记中的来源与类型用于辅助判断。</p><p>素材来自项目组交付的原游戏素材。网页版沿用人物、场景、CG、音乐与既有配音，新增探索连接与按需资源加载。音乐署名可在下方查阅。</p><h3>与你在知乎继续讨论</h3><p>不同人物的说法为什么冲突？你会凭什么作判断？探索手记中的话题入口可打开知乎搜索，继续阅读与讨论。</p><h3>进度与对话</h3><p>阅读存档保存在当前浏览器，可导出迁移。AI 对话保存在服务器的随机会话下，仅用于人物回应与手记；请勿输入个人敏感资料。知乎连接为可选功能，可在下方管理。</p><p><a href="${BASE}credits.html" target="_blank" rel="noopener">音乐与素材署名 ↗</a></p><button id="zhihu-connect">知乎账号连接</button> <button id="watch-op">重看片头</button></section>`);bind('#watch-op',()=>startOpening(()=>about()));bind('#zhihu-connect',zhihuAccount);}
function zhihuAccount(){page('知乎连接','<section id="zhihu-account" class="about-copy"><p>正在读取连接状态…</p></section>');void showZhihuAccount($('#zhihu-account'));}
function showInlineGame(id:string,done:()=>void){resetView();state='games';import('./minigames').then(m=>{disposeExplore=m.launchMiniGame(app,id,score=>{exploration.games[id]=Math.max(exploration.games[id]??0,score);saveAuto();disposeExplore=null;done();});});}
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement||e.target instanceof HTMLSelectElement||e.isComposing)return;if(state==='vn'&&[' ','Enter'].includes(e.key)&&!(e.target instanceof HTMLButtonElement)){e.preventDefault();nextText();}else if(state==='transition'&&[' ','Enter','Escape'].includes(e.key)){e.preventDefault();$('#transition')?.click();}else if(e.key==='Escape'){if(state==='page')returnFromPage();else if(state==='vn')settings();}});
window.addEventListener('pagehide',()=>{if(story&&['vn','explore'].includes(state))saveAuto();});
initialize().then(()=>{story=new StoryEngine(catalog.chapter);syncAudio();document.documentElement.classList.toggle('reduced-motion',!profile.settings.motion);title();if(location.hash.startsWith('#zhihu')){window.history.replaceState(null,'',BASE);zhihuAccount();}}).catch(e=>{app.innerHTML=`<div class="loading-page"><h1>故事暂未展开</h1><p>${esc(e.message)}</p><button onclick="location.reload()">重新加载</button></div>`;});
