import {art,asset,character,esc,$,bind,profile,persist,toast} from './core';
const ROOT='generated/minigames/gpt-image-2.5-flare/';
const img=(name:string)=>asset(ROOT+name+'.png');
const GAMES=[['embroidery','锦绣配色','记住花样，凭记忆配好四色丝线','embroidery'],['town','古镇寻物','在街市里寻回五件小物','town'],['tea','茶席礼仪','依照五条规则，排一席清茶','tea'],['rain','雨巷归途','躲过落物，平安穿过雨巷','rain']] as const;
export function showGameHub(root:HTMLElement,back:()=>void){root.innerHTML=`<main class="paper-page"><header class="page-heading"><button id="hub-back" class="text-link">‹ 返回</button><div><p class="eyebrow">卷中闲趣</p><h1>游艺小集</h1></div><span class="seal">游</span></header><p class="page-intro">原游戏的四款小游戏。随时重玩，最好成绩会保留。</p><div class="game-hub-grid">${GAMES.map(([id,title,desc,bg])=>`<button class="game-hub-card" data-game="${id}" style="--game-bg:url('${img('backdrop-'+bg)}')"><div><small>${profile.best[id]!==undefined?'最好成绩 '+profile.best[id]:'尚未游玩'}</small><h2>${title}</h2><p>${desc}</p><span>进入 →</span></div></button>`).join('')}</div></main>`;bind('#hub-back',back,root);GAMES.forEach(([id])=>bind(`[data-game="${id}"]`,()=>{launchMiniGame(root,id,score=>{profile.best[id]=Math.max(profile.best[id]??0,score);persist();showGameHub(root,back);});},root));}
const NAMES:Record<string,string>={embroidery:'锦绣配色',town:'古镇寻物',tea:'茶席礼仪',rain:'雨巷归途',crown:'轻解凤冠',evidence:'证据摆在眼前',argument:'整理说服顺序',tavern:'串联酒楼证词',swim:'划 · 蹬 · 收',medicine:'药碗与脚步',memorial:'奏折上的三层意思',noodles:'一碗长寿面','place-zither':'花厅摆琴','accounts-silk':'绸缎庄的账','accounts-rouge':'胭脂铺的账','accounts-grain':'粮铺的账'};
export function launchMiniGame(root:HTMLElement,id:string,done:(score:number)=>void){let disposed=false,finished=false;let childDispose:(()=>void)|undefined;const timers:number[]=[];const cleanup:(()=>void)[]=[];let score=0;
 function later(fn:()=>void,ms:number){const t=window.setTimeout(()=>{if(!disposed&&!finished)fn();},ms);timers.push(t);return t;}
 function interval(fn:()=>void,ms:number){const t=window.setInterval(()=>{if(!disposed&&!finished)fn();},ms);timers.push(t);return t;}
 const stop=()=>{timers.forEach(t=>{clearInterval(t);clearTimeout(t);});cleanup.forEach(fn=>fn());};
 function end(value:number,text:string){if(disposed||finished)return;finished=true;score=value;stop();const overlay=document.createElement('section');overlay.className='mini-result';overlay.innerHTML=`<span class="seal">${value>=60?'成':'试'}</span><p class="eyebrow">${esc(NAMES[id]??'途中小事')}</p><h2>${value>=60?'这一回，做得妥当':'这一回，也有收获'}</h2><p>${esc(text)}</p><strong>${value} 分</strong><div><button id="mini-again">再试一次</button><button id="mini-done" class="primary">收下这一程 →</button></div>`;root.append(overlay);bind('#mini-done',()=>{dispose();done(score);},root);bind('#mini-again',()=>{dispose();childDispose=launchMiniGame(root,id,done);},root);}
 function shell(instruction:string,body:string,bg='tea'){root.innerHTML=`<main class="mini-page" style="--mini-bg:url('${img('backdrop-'+bg)}')"><header class="mini-header"><div><p class="eyebrow">卷中游艺</p><h1>${esc(NAMES[id]??'途中小事')}</h1></div><button id="mini-help" class="glass">千芷提示</button></header><p class="mini-instruction">${esc(instruction)}</p><div id="mini-board" class="mini-board">${body}</div><footer><span id="mini-status">慢慢来，探索里可以重试。</span><button id="mini-assist">由千芷协助完成</button></footer></main>`;bind('#mini-help',()=>toast(instruction),root);bind('#mini-assist',()=>end(0,'千芷帮着完成了这件事。下次也可以自己再试试。'),root);}
 const status=(text:string)=>{const el=$('#mini-status',root);if(el)el.textContent=text;};
 function orderGame(labels:string[],correct:number[],instruction:string){let picks:number[]=[],mistakes=0;shell(instruction,`<div class="order-slots">${labels.map((_,i)=>`<div id="order-${i}" class="order-slot">${i+1}</div>`).join('')}</div><div class="order-options">${labels.map((l,i)=>`<button data-order="${i}">${esc(l)}</button>`).sort(()=>Math.random()-.5).join('')}</div><button id="order-reset">重新排列</button>`);const reset=()=>{picks=[];labels.forEach((_,i)=>{$('#order-'+i,root).textContent=String(i+1);$<HTMLButtonElement>(`[data-order="${i}"]`,root).disabled=false;});};bind('#order-reset',reset,root);labels.forEach((l,i)=>bind(`[data-order="${i}"]`,()=>{if(picks.includes(i))return;const n=picks.length;picks.push(i);$('#order-'+n,root).textContent=l;$<HTMLButtonElement>(`[data-order="${i}"]`,root).disabled=true;if(i!==correct[n]){mistakes++;status('这个顺序似乎不太妥当，可以重新排列。');}if(picks.length===labels.length){if(picks.every((v,j)=>v===correct[j]))end(Math.max(60,100-mistakes*10),'顺序已经理清。带着这份准备，回到故事里。');else{status('顺序还可再想一想。点击「重新排列」重试。');}}},root));}
 if(id==='embroidery'){
  const colors=['朱砂红','玉绿','哑金','靛青'],files=['vermilion','jade','gold','indigo'],target=Array.from({length:4},()=>Math.floor(Math.random()*4));let picks:number[]=[],revealed=true;
  shell('先用四秒记住丝线顺序，再依次选择相同的颜色。',`<div class="thread-slots">${target.map((v,i)=>`<div id="thread-${i}"><img src="${img('items/thread-'+files[v])}" alt="${colors[v]}"><span>${colors[v]}</span></div>`).join('')}</div><div class="thread-options">${colors.map((c,i)=>`<button data-thread="${i}" disabled><img src="${img('items/thread-'+files[i])}" alt="${c}">${c}</button>`).join('')}</div>`,'embroidery');let left=4;status('记忆时间 4 秒');interval(()=>{left--;if(left>0)status('记忆时间 '+left+' 秒');},1000);later(()=>{revealed=false;target.forEach((_,i)=>$('#thread-'+i,root).innerHTML='<span>？</span>');root.querySelectorAll<HTMLButtonElement>('[data-thread]').forEach(b=>b.disabled=false);status('凭记忆依次配线。');},4000);colors.forEach((c,i)=>bind(`[data-thread="${i}"]`,()=>{if(revealed||picks.length>=4)return;$('#thread-'+picks.length,root).innerHTML=`<img src="${img('items/thread-'+files[i])}" alt="${c}"><span>${c}</span>`;picks.push(i);if(picks.length===4)end(picks.filter((v,j)=>v===target[j]).length*25,'丝线次序已经留下。配色既靠记忆，也靠耐心。');},root));
 }else if(id==='tea'){
  const names=['茶壶','茶则','茶巾','茶盏','香炉'],files=['tea-pot','tea-scoop','tea-towel','tea-bowl','incense-burner'];let picks:number[]=[];
  shell('茶壶第一、茶则紧随其后、茶巾在茶盏之前、香炉最后；茶盏不能第二。',`<div class="tea-rules"><p>一、茶壶为席首。　二、茶则紧随其后。</p><p>三、茶巾在茶盏之前。　四、香炉末位。　五、茶盏不可第二。</p><small>这是游戏排序规则，不作为真实茶礼制度。</small></div><div class="tea-slots">${names.map((_,i)=>`<button id="tea-slot-${i}">${i+1}</button>`).join('')}</div><div class="tea-items">${names.map((n,i)=>`<button data-tea="${i}"><img src="${img('items/'+files[i])}" alt="${n}"><span>${n}</span></button>`).join('')}</div><button id="tea-submit" class="primary">确认这席清茶</button>`);function draw(){names.forEach((_,i)=>{$('#tea-slot-'+i,root).innerHTML=picks[i]!==undefined?`<img src="${img('items/'+files[picks[i]])}" alt="${names[picks[i]]}">`:String(i+1);$<HTMLButtonElement>(`[data-tea="${i}"]`,root).disabled=picks.includes(i);});}names.forEach((_,i)=>{bind(`[data-tea="${i}"]`,()=>{if(!picks.includes(i)){picks.push(i);draw();}},root);bind('#tea-slot-'+i,()=>{picks.splice(i,1);draw();},root);});bind('#tea-submit',()=>{if(picks.length<5){toast('还没有摆齐五件器物。');return;}if(picks.every((v,i)=>v===i))end(100,'五条规则互相印证，一席清茶已经摆妥。');else status('还有规则没有满足。点击席位收回器物，再试一次。');},root);
 }else if(id==='town'){
  const names=['玉坠','红丝带','铜铃','折扇','药包'],files=['clue-jade-pendant','clue-silk-ribbon','clue-bronze-bell','clue-folding-fan','clue-medicine-packet'];const spots=[[14,24],[42,63],[71,29],[83,72],[29,80]];let found=new Set<number>(),miss=0;
  shell('点击画中藏着的五件小物：玉坠、红丝带、铜铃、折扇、药包。',`<div class="town-picture" id="town-picture" style="background-image:url('${img('backdrop-town')}')">${names.map((n,i)=>`<button data-found="${i}" style="left:${spots[i][0]}%;top:${spots[i][1]}%" aria-label="${n}"><img src="${img('items/'+files[i])}" alt="${n}"></button>`).join('')}</div><div class="found-list">${names.map((n,i)=>`<span id="found-${i}">○ ${n}</span>`).join('')}</div>`,'town');bind('#town-picture',()=>{miss++;status('这里没有线索。已找到 '+found.size+' / 5');if(miss%3===0){const next=names.findIndex((_,i)=>!found.has(i));$(`[data-found="${next}"]`,root)?.classList.add('hinted');}},root);names.forEach((n,i)=>bind(`[data-found="${i}"]`,()=>{if(found.has(i))return;found.add(i);$(`[data-found="${i}"]`,root).style.visibility='hidden';$('#found-'+i,root).textContent='✓ '+n;status('已找到 '+found.size+' / 5');if(found.size===5)end(Math.max(50,100-miss*5),'五件小物都寻回来了。街市里的细节，比想象中多。');},root));root.querySelectorAll<HTMLElement>('[data-found]').forEach(e=>e.addEventListener('click',e=>e.stopPropagation()));
 }else if(id==='rain'){
  shell('用左右方向键或下方按钮换道，躲过落物，坚持二十秒。',`<div id="rain-road" class="rain-road"><div class="rain-lanes"><i></i><i></i><i></i></div><img id="rain-player" src="${character('char-huaqian')}" alt="华浅"></div><div class="rain-controls"><button id="rain-left">← 向左</button><strong id="rain-life">余下 20 秒 · 3 次机会</strong><button id="rain-right">向右 →</button></div>`,'rain');let lane=1,life=3,start=performance.now(),last=start,spawn=start,objects:{el:HTMLElement;lane:number;y:number}[]=[];let raf=0;const road=$('#rain-road',root),player=$('#rain-player',root);const move=(d:number)=>{lane=Math.max(0,Math.min(2,lane+d));player.style.left=(lane*30+20)+'%';};move(0);bind('#rain-left',()=>move(-1),root);bind('#rain-right',()=>move(1),root);const key=(e:KeyboardEvent)=>{if(['ArrowLeft','a','ArrowRight','d'].includes(e.key)){e.preventDefault();move(['ArrowLeft','a'].includes(e.key)?-1:1);}};window.addEventListener('keydown',key);cleanup.push(()=>{window.removeEventListener('keydown',key);cancelAnimationFrame(raf);});function frame(now:number){if(disposed||finished)return;const dt=Math.min((now-last)/1000,.08);last=now;const elapsed=(now-start)/1000;if(elapsed>=20){end(Math.max(0,100-(3-life)*25),'走过雨巷，这一程平安归来。');return;}if(now-spawn>Math.max(480,1000-elapsed*20)){spawn=now;const l=Math.floor(Math.random()*3),el=document.createElement('img');el.className='rain-object';el.setAttribute('src',img('items/'+['fall-roof-tile','fall-flower-pot','fall-branch'][Math.floor(Math.random()*3)]));el.style.left=(l*30+20)+'%';road.append(el);objects.push({el,lane:l,y:-10});}for(const o of [...objects]){o.y+=dt*(30+elapsed);o.el.style.top=o.y+'%';if(o.y>78&&o.y<92&&o.lane===lane){o.el.remove();objects=objects.filter(x=>x!==o);life--;player.classList.add('hit');later(()=>player.classList.remove('hit'),250);if(life<=0){end(0,'雨势太急，先在檐下避一避。可以重试，也可以继续故事。');return;}}else if(o.y>110){o.el.remove();objects=objects.filter(x=>x!==o);}}$('#rain-life',root).textContent=`余下 ${Math.ceil(20-elapsed)} 秒 · ${life} 次机会`;raf=requestAnimationFrame(frame);}raf=requestAnimationFrame(frame);
 }else if(id.startsWith('accounts')){
  const entries:Record<string,[number,number,number]>={'accounts-silk':[480,210,90],'accounts-rouge':[360,145,75],'accounts-grain':[650,390,60]};const [a,b,c]=entries[id];const answer=a-b-c;
  shell('核对收入、成本与工钱，把能留下的余钱算清楚。',`<div class="account-paper"><h2>月结账册</h2><dl><dt>入账</dt><dd>${a} 两</dd><dt>采买 / 原料</dt><dd>− ${b} 两</dd><dt>工钱 / 运费</dt><dd>− ${c} 两</dd></dl><label>余钱 <input id="account-answer" type="number" min="0" max="1000" placeholder="？"> 两</label><button id="account-submit" class="primary">记入账册</button><p id="account-hint"></p></div>`);bind('#account-submit',()=>{const v=$<HTMLInputElement>('#account-answer',root).value;if(v!==''&&Number(v)===answer)end(100,`${a} − ${b} − ${c} = ${answer} 两。账册已核对。`);else $('#account-hint',root).textContent=`先从 ${a} 两里扣去 ${b} 两，还余 ${a-b} 两，再减去 ${c} 两。`;},root);
 }else if(id==='argument')orderGame(['从华美人的话开头','指出皇室在留意华府','提醒华府收敛锋芒','把减罪说成消除皇上疑心'],[0,1,2,3],'把四张论据按开口的顺序排列。先从共同关切出发，最后说明解决办法。');
 else if(id==='evidence'){
  const rows=[['没有目击者','暂不足以认定偷窃'],['钱袋尚未出示','还需核实赃物'],['商人命人殴打','不能代替证据']];let n=0;shell('给三条线索各找一个恰当的判断。',`<div id="evidence-question" class="deduction-card"></div>`,'town');function ask(){const [label,answer]=rows[n];$('#evidence-question',root).innerHTML=`<p class="eyebrow">证据 ${n+1}/3</p><h2>${label}</h2><div class="deduction-options"><button data-answer="yes">${answer}</button><button data-answer="no">所以孩子一定是小偷</button></div>`;bind('[data-answer="yes"]',()=>{n++;if(n===3)end(100,'没有目击、没有出示赃物，指控仍待核实。接下来，当面问清楚。');else ask();},root);bind('[data-answer="no"]',()=>status('这项结论超出了眼前证据。再想一想。'),root);}ask();
 }else if(id==='tavern'){
  const rows=[['“她不愿意被华公子纠缠。”','当事人陈述'],['“华浅一定会替华家撑腰。”','人物推断'],['“小二没看见事情起头。”','有限目击']];let n=0;shell('把证词和判断分开。每句话，先看是谁说的、亲见了多少。',`<div id="evidence-question" class="deduction-card"></div>`);function ask(){const [label,answer]=rows[n];$('#evidence-question',root).innerHTML=`<p class="eyebrow">核对 ${n+1}/3</p><h2>${label}</h2><div class="deduction-options">${['当事人陈述','人物推断','有限目击'].map(a=>`<button data-kind="${a}">${a}</button>`).join('')}</div>`;root.querySelectorAll<HTMLButtonElement>('[data-kind]').forEach(b=>b.onclick=()=>{if(b.dataset.kind!==answer){status('先看信息来源：亲历、立场，还是只看到一部分？');return;}n++;if(n===3)end(100,'证词按来源归位；人物的猜测仍只是猜测。现在，可以出面处理。');else ask();});}ask();
 }else if(id==='crown')orderGame(['左外簪','右外簪','左上簪','右上簪','左内簪','右内簪'],[0,1,2,3,4,5],'从外侧到内侧，成对轻轻取下六根簪。先外，后上，再内。');
 else if(id==='swim'){
  let hits=0,tries=0,start=performance.now();shell('跟着呼吸的节奏。游标进入中间的绿色区域时点按，完成八拍。',`<div class="swim-waves"><h2 id="swim-word">划</h2><div class="rhythm-bar"><span class="rhythm-window"></span><i id="rhythm-cursor"></i></div><button id="rhythm-tap" class="primary">划 · 蹬 · 收</button><p id="rhythm-count">0 / 8</p></div>`,'rain');interval(()=>{const phase=((performance.now()-start)%1500)/1500;$('#rhythm-cursor',root).style.left=(phase*100)+'%';},25);bind('#rhythm-tap',()=>{const phase=((performance.now()-start)%1500)/1500;tries++;if(phase>.32&&phase<.7){hits++;status('呼吸稳住了。');}else status('这一拍稍乱，再跟一次节奏。');$('#swim-word',root).textContent=['划','蹬','收'][tries%3];$('#rhythm-count',root).textContent=`${tries} / 8 · 命中 ${hits}`;if(tries===8)end(Math.round(hits/8*100),'水声终于离耳边远了一些。原剧情中的上岸方式由此前选择保留。');},root);
 }else if(id==='medicine'){
  let back=false,hold=0,holding=false;const start=performance.now();shell('这是一段虚构的角色小把戏。千芷背过身时按住按钮 1.5 秒，被看见就收手。',`<div class="medicine-stage"><img src="${character('char-qianzhi')}" alt="千芷"><div><h2 id="medicine-facing">千芷正看着这边</h2><div class="hold-progress"><i id="medicine-progress"></i></div><button id="medicine-hold">按住 · 挪开药碗</button><p>故事行为，不是现实的用药建议。</p></div></div>`);const b=$<HTMLButtonElement>('#medicine-hold',root);b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);holding=true;};b.onpointerup=()=>holding=false;b.onpointercancel=()=>holding=false;interval(()=>{back=Math.floor((performance.now()-start)/2300)%2===1;$('#medicine-facing',root).textContent=back?'千芷转身收拾东西':'千芷正看着这边';b.classList.toggle('safe',back);if(holding&&!back){end(0,'千芷看见了，药碗还是老老实实留在手边。这一天也过去了。');return;}if(holding&&back)hold+=40;else hold=Math.max(0,hold-12);$('#medicine-progress',root).style.width=Math.min(100,hold/15)+'%';if(hold>=1500)end(100,'趁她转身，一段小插曲悄悄过去。');},40);
 }else if(id==='memorial'){
  let found=new Set<number>();const lines=['华深行事，过错累累。','华相教子不严，纵容失察。','家门如此，朝中行事何以自明？'];shell('这是依据原剧情改写的奏折摘要。点出罪状、管教责任与对华府的质疑。',`<div class="memorial-paper"><span class="seal">奏</span>${lines.map((t,i)=>`<button data-memorial="${i}">${t}</button>`).join('')}<small>游戏摘要，非历史奏折原文</small></div>`);lines.forEach((_,i)=>bind(`[data-memorial="${i}"]`,()=>{found.add(i);$(`[data-memorial="${i}"]`,root).classList.add('marked');status(['罪状指向华深。','“教子不严”指向华相。','矛头由个人转向华府整体。'][i]);if(found.size===3)later(()=>end(100,'表面参的是华深，字里行间却把整个华府推到了面前。'),900);},root));
 }else if(id==='place-zither'){
  shell('把名琴放到花厅正中的琴案。可拖动，也可先点琴再点琴案。',`<div class="zither-placement"><button id="zither-piece" draggable="true"><img src="${img('backdrop-embroidery')}" alt="琴案准备"><span>千芷备好的名琴</span></button><button id="zither-target">花厅琴案<br><small>放在这里</small></button></div>`);let selected=false;const piece=$('#zither-piece',root),target=$('#zither-target',root);piece.ondragstart=e=>{selected=true;e.dataTransfer?.setData('text/plain','zither');};piece.onclick=()=>{selected=true;piece.classList.add('selected');status('再点琴案，轻轻放下。');};target.ondragover=e=>e.preventDefault();target.ondrop=e=>{e.preventDefault();if(selected)end(100,'名琴已在花厅正中摆妥。');};target.onclick=()=>{if(selected)end(100,'名琴已在花厅正中摆妥。');else toast('先拿起名琴。');};
 }else if(id==='noodles'){
  let step=0,clicks=0,timing=0;const names=['和面','拉面','下锅','添浇头'];shell('和面、拉面、下锅、添浇头。一步一步，端出一碗自己的长寿面。',`<div class="noodle-steps">${names.map((n,i)=>`<span id="noodle-step-${i}">${i+1} · ${n}</span>`).join('')}</div><div id="noodle-work" class="noodle-work"></div>`);function show(){names.forEach((_,i)=>$('#noodle-step-'+i,root).classList.toggle('done',i<step));const work=$('#noodle-work',root);if(step===0){work.innerHTML='<div class="flour-bowl">面</div><h2>把面团揉匀</h2><button id="mix" class="primary">揉一揉 · 0 / 6</button>';bind('#mix',()=>{clicks++;$('#mix',root).textContent='揉一揉 · '+clicks+' / 6';if(clicks>=6){step++;show();}},root);}else if(step===1){work.innerHTML='<div class="noodle-strand" id="strand"></div><h2>把面慢慢拉长</h2><input id="stretch" aria-label="拉面的长度" type="range" min="0" max="100" value="0"><button id="stretch-done" class="primary">收好面条</button>';$<HTMLInputElement>('#stretch',root).oninput=e=>$('#strand',root).style.width=(15+Number((e.target as HTMLInputElement).value)*.7)+'%';bind('#stretch-done',()=>{if(Number($<HTMLInputElement>('#stretch',root).value)<60){toast('再稍稍拉长一些。');return;}step++;show();},root);}else if(step===2){work.innerHTML='<div class="noodle-pot">汤</div><h2 id="boil-clock">热汤翻滚 · 0 秒</h2><button id="lift" class="primary">起锅</button>';const start=performance.now();const ti=interval(()=>{timing=(performance.now()-start)/1000;$('#boil-clock',root).textContent='热汤翻滚 · '+Math.floor(timing)+' 秒';},200);bind('#lift',()=>{if(timing<6){toast('面条还要再煮一会儿。');return;}clearInterval(ti);step++;show();},root);}else{work.innerHTML='<h2>最后，添一份心意</h2><div class="topping-options"><button data-topping="清汤">清汤</button><button data-topping="葱油">葱油</button><button data-topping="卧蛋">卧蛋</button></div>';root.querySelectorAll<HTMLElement>('[data-topping]').forEach(b=>b.onclick=()=>end(timing>=6&&timing<=11?100:75,'一碗'+b.dataset.topping+'长寿面做好了。接下来，把它端回宴席。'));}}show();
 }else{shell('歇一歇，继续眼前的故事。','<button id="generic-done" class="primary">继续</button>');bind('#generic-done',()=>end(100,'已完成。'),root);}
 function dispose(){if(disposed)return;disposed=true;stop();}
 return ()=>{childDispose?.();dispose();};
}
